# name  = input("Enter yoour name: ")

# print(f"good afternoon {name} ")
# print(f"good afternoon {name} ")
# print(f"good afternoon {name} ")
# print(f"good afternoon {name} ")
# print(f"good afternoon {name} ")
# print(f"good afternoon {name} ")
# print(f"good afternoon {name} ")
# print(f"good afternoon {name} ")
# print(f"good afternoon {name} ")